version: '2'

networks:
  kafka2clickhouse:
   external: 
    name: kafka2clickhouse


services:
  clickhouse-server:
    image: 'yandex/clickhouse-server:21.1-alpine'
    container_name: clickhouse-server
    networks:
      - kafka2clickhouse

