version: '2'

networks:
  kafka2clickhouse:
   external: 
    name: kafka2clickhouse

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    container_name: zookeeper
    networks:
      - kafka2clickhouse
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    container_name: kafka
    networks:
      - kafka2clickhouse
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
