FROM python:3.6.9-slim-buster as base
WORKDIR /usr/src/app
RUN apt-get update -qq && \
    apt-get install -yqq apt-utils && \
    apt-get install -yqq --no-install-recommends vim &&\
    #Clean-up
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN pip install kafka-python==2.0.2
ADD . . 
ENTRYPOINT ["python", "kafka_producer.py"]